# Generated by Django 2.2.6 on 2019-10-27 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teamy', '0002_department_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Club')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ManyToManyField(to='teamy.Club', verbose_name='Club'),
        ),
    ]
